#FROM python:3
FROM python:2

COPY requirements ./requirements
RUN pip install --no-cache-dir -r requirements/prod.txt


COPY src /data/src

COPY container-entrypoint.sh /entry
RUN chmod 0755 /entry

CMD ["prod"]
ENTRYPOINT ["/entry"]